<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mrr_pcd_create</name>
  <version>0.1.0</version>
  <description>Master-slave architecture for distributed pointcloud capture via action servers. UI master + multiple robot slaves.</description>
  <maintainer email="todo@todo.com">todo</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>mrr_pcd_create_msgs</depend>
  <depend>hector_multi_robot_msgs</depend>

  <build_depend>libpcl-dev</build_depend>
  <depend>libglfw3-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
